/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SegurosRouteImport } from './routes/seguros'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PatrimonioRouteImport } from './routes/patrimonio'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as MeuPatrimonioRouteImport } from './routes/meu-patrimonio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InternacionalRouteImport } from './routes/internacional'
import { Route as CriptoRouteImport } from './routes/cripto'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComparadorRouteImport } from './routes/comparador'
import { Route as CarteirasRouteImport } from './routes/carteiras'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarteirasSlugRouteImport } from './routes/carteiras.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AcaoTickerRouteImport } from './routes/acao.$ticker'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurosRoute = SegurosRouteImport.update({
  id: '/seguros',
  path: '/seguros',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrimonioRoute = PatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuPatrimonioRoute = MeuPatrimonioRouteImport.update({
  id: '/meu-patrimonio',
  path: '/meu-patrimonio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InternacionalRoute = InternacionalRouteImport.update({
  id: '/internacional',
  path: '/internacional',
  getParentRoute: () => rootRouteImport,
} as any)
const CriptoRoute = CriptoRouteImport.update({
  id: '/cripto',
  path: '/cripto',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparadorRoute = ComparadorRouteImport.update({
  id: '/comparador',
  path: '/comparador',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteirasRoute = CarteirasRouteImport.update({
  id: '/carteiras',
  path: '/carteiras',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteirasSlugRoute = CarteirasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CarteirasRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AcaoTickerRoute = AcaoTickerRouteImport.update({
  id: '/acao/$ticker',
  path: '/acao/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/carteiras': typeof CarteirasRouteWithChildren
  '/comparador': typeof ComparadorRoute
  '/contato': typeof ContatoRoute
  '/cripto': typeof CriptoRoute
  '/internacional': typeof InternacionalRoute
  '/login': typeof LoginRoute
  '/meu-patrimonio': typeof MeuPatrimonioRoute
  '/noticias': typeof NoticiasRoute
  '/onboarding': typeof OnboardingRoute
  '/patrimonio': typeof PatrimonioRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/seguranca': typeof SegurancaRoute
  '/seguros': typeof SegurosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/acao/$ticker': typeof AcaoTickerRoute
  '/api/chat': typeof ApiChatRoute
  '/carteiras/$slug': typeof CarteirasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/carteiras': typeof CarteirasRouteWithChildren
  '/comparador': typeof ComparadorRoute
  '/contato': typeof ContatoRoute
  '/cripto': typeof CriptoRoute
  '/internacional': typeof InternacionalRoute
  '/login': typeof LoginRoute
  '/meu-patrimonio': typeof MeuPatrimonioRoute
  '/noticias': typeof NoticiasRoute
  '/onboarding': typeof OnboardingRoute
  '/patrimonio': typeof PatrimonioRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/seguranca': typeof SegurancaRoute
  '/seguros': typeof SegurosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/acao/$ticker': typeof AcaoTickerRoute
  '/api/chat': typeof ApiChatRoute
  '/carteiras/$slug': typeof CarteirasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/carteiras': typeof CarteirasRouteWithChildren
  '/comparador': typeof ComparadorRoute
  '/contato': typeof ContatoRoute
  '/cripto': typeof CriptoRoute
  '/internacional': typeof InternacionalRoute
  '/login': typeof LoginRoute
  '/meu-patrimonio': typeof MeuPatrimonioRoute
  '/noticias': typeof NoticiasRoute
  '/onboarding': typeof OnboardingRoute
  '/patrimonio': typeof PatrimonioRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/seguranca': typeof SegurancaRoute
  '/seguros': typeof SegurosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/acao/$ticker': typeof AcaoTickerRoute
  '/api/chat': typeof ApiChatRoute
  '/carteiras/$slug': typeof CarteirasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor'
    | '/carteiras'
    | '/comparador'
    | '/contato'
    | '/cripto'
    | '/internacional'
    | '/login'
    | '/meu-patrimonio'
    | '/noticias'
    | '/onboarding'
    | '/patrimonio'
    | '/perfil'
    | '/privacidade'
    | '/seguranca'
    | '/seguros'
    | '/sitemap.xml'
    | '/termos'
    | '/acao/$ticker'
    | '/api/chat'
    | '/carteiras/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisor'
    | '/carteiras'
    | '/comparador'
    | '/contato'
    | '/cripto'
    | '/internacional'
    | '/login'
    | '/meu-patrimonio'
    | '/noticias'
    | '/onboarding'
    | '/patrimonio'
    | '/perfil'
    | '/privacidade'
    | '/seguranca'
    | '/seguros'
    | '/sitemap.xml'
    | '/termos'
    | '/acao/$ticker'
    | '/api/chat'
    | '/carteiras/$slug'
  id:
    | '__root__'
    | '/'
    | '/advisor'
    | '/carteiras'
    | '/comparador'
    | '/contato'
    | '/cripto'
    | '/internacional'
    | '/login'
    | '/meu-patrimonio'
    | '/noticias'
    | '/onboarding'
    | '/patrimonio'
    | '/perfil'
    | '/privacidade'
    | '/seguranca'
    | '/seguros'
    | '/sitemap.xml'
    | '/termos'
    | '/acao/$ticker'
    | '/api/chat'
    | '/carteiras/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRoute
  CarteirasRoute: typeof CarteirasRouteWithChildren
  ComparadorRoute: typeof ComparadorRoute
  ContatoRoute: typeof ContatoRoute
  CriptoRoute: typeof CriptoRoute
  InternacionalRoute: typeof InternacionalRoute
  LoginRoute: typeof LoginRoute
  MeuPatrimonioRoute: typeof MeuPatrimonioRoute
  NoticiasRoute: typeof NoticiasRoute
  OnboardingRoute: typeof OnboardingRoute
  PatrimonioRoute: typeof PatrimonioRoute
  PerfilRoute: typeof PerfilRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SegurancaRoute: typeof SegurancaRoute
  SegurosRoute: typeof SegurosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  AcaoTickerRoute: typeof AcaoTickerRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguros': {
      id: '/seguros'
      path: '/seguros'
      fullPath: '/seguros'
      preLoaderRoute: typeof SegurosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrimonio': {
      id: '/patrimonio'
      path: '/patrimonio'
      fullPath: '/patrimonio'
      preLoaderRoute: typeof PatrimonioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-patrimonio': {
      id: '/meu-patrimonio'
      path: '/meu-patrimonio'
      fullPath: '/meu-patrimonio'
      preLoaderRoute: typeof MeuPatrimonioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internacional': {
      id: '/internacional'
      path: '/internacional'
      fullPath: '/internacional'
      preLoaderRoute: typeof InternacionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cripto': {
      id: '/cripto'
      path: '/cripto'
      fullPath: '/cripto'
      preLoaderRoute: typeof CriptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparador': {
      id: '/comparador'
      path: '/comparador'
      fullPath: '/comparador'
      preLoaderRoute: typeof ComparadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteiras': {
      id: '/carteiras'
      path: '/carteiras'
      fullPath: '/carteiras'
      preLoaderRoute: typeof CarteirasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteiras/$slug': {
      id: '/carteiras/$slug'
      path: '/$slug'
      fullPath: '/carteiras/$slug'
      preLoaderRoute: typeof CarteirasSlugRouteImport
      parentRoute: typeof CarteirasRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acao/$ticker': {
      id: '/acao/$ticker'
      path: '/acao/$ticker'
      fullPath: '/acao/$ticker'
      preLoaderRoute: typeof AcaoTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CarteirasRouteChildren {
  CarteirasSlugRoute: typeof CarteirasSlugRoute
}

const CarteirasRouteChildren: CarteirasRouteChildren = {
  CarteirasSlugRoute: CarteirasSlugRoute,
}

const CarteirasRouteWithChildren = CarteirasRoute._addFileChildren(
  CarteirasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRoute,
  CarteirasRoute: CarteirasRouteWithChildren,
  ComparadorRoute: ComparadorRoute,
  ContatoRoute: ContatoRoute,
  CriptoRoute: CriptoRoute,
  InternacionalRoute: InternacionalRoute,
  LoginRoute: LoginRoute,
  MeuPatrimonioRoute: MeuPatrimonioRoute,
  NoticiasRoute: NoticiasRoute,
  OnboardingRoute: OnboardingRoute,
  PatrimonioRoute: PatrimonioRoute,
  PerfilRoute: PerfilRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SegurancaRoute: SegurancaRoute,
  SegurosRoute: SegurosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  AcaoTickerRoute: AcaoTickerRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
